railsService:
  name: railsfrontend
  image: judekhay/rails-service # replace with repo name
  tag: v0.0.3
  replicas: 2
  label:
    app: rubyrails
  namespace: default
  port: 3000 # replace with port number

pythonService:
  name: pythonapi
  image: judekhay/pythonapi-service # replace with repo name
  tag: v0.0.3
  replicas: 1
  label:
    app: api
  namespace: default
  port: 8890 # replace with port number

goService:
  name: goservice
  image: judekhay/go-service # replace with repo name
  tag: v0.0.3
  replicas: 3
  label:
    app: goservice
  namespace: default
  port: 8080 # replace with port number

#  CLI command: helm install my-release-name ./mychartPATH -f ./values-PATH
